### ISSUE TITLE
Q8 Support?

### ISSUE THREAD

**Issue by cakir-enes** [adophoxia/VIAL-for-Keychron#2]
I tried to add it by using https://github.com/qmk/qmk_firmware/tree/master/keyboards/keychron/q8 but had some errors regarding LED, it would be nice if you could add support for q8 as well.

**Comment by adophoxia** [comment]
A commit was added my [`vial-keychron`](https://github.com/adophoxia/vial-qmk/tree/vial-keychron) branch just now related to the [Keychron Q8.](https://github.com/vial-kb/vial-qmk/commit/5c83fef09204845447a03044fd1aeaba06b73ff1)

**Comment by cakir-enes** [comment]
thank you
