### ISSUE TITLE
Q2 Vial File

### ISSUE THREAD

**Issue by zer0trip** [adophoxia/VIAL-for-Keychron#3]
It looks like there is no vial file for the Keychron Q2 so it fails to build. Hopefully I'm not doing something wrong.

**Comment by adophoxia** [comment]
What Q2 variant are you trying to build and are you doing this with the `vial-keychron` branch?

**Comment by zer0trip** [comment]
rev_0111 and I did use the vial-keychron branch.

**Comment by adophoxia** [comment]
Are you able to show the log of the terminal (or MSYS) that shows the error where the build fails?

**Comment by zer0trip** [comment]
![image](https://user-images.githubusercontent.com/17455247/211449405-54188035-6473-4eb4-a20c-48e69bb537fb.png)

**Comment by adophoxia** [comment]
Ah. Looking at the branch, it seems like I haven't added an entry for it for some reason. I did set up another branch specifically for the Q2 [here](https://github.com/adophoxia/vial-qmk/tree/vial-keychron-q2) with some updated changes.

**Comment by zer0trip** [comment]
That branch worked perfectly. Thank you!!
