### ISSUE TITLE
V Series Support?

### ISSUE THREAD

**Issue by spencerthayer** [adophoxia/VIAL-for-Keychron#4]
Have you had any confirmation that the V series works? I would like to get my v3 away from VIA as soon as possible LOL.

**Comment by adophoxia** [comment]
If by "works", as in I can compile the firmware for them, yes. So far, every V series boards works. Just a matter of doing some last minute checkups to make sure they work right.

**Comment by spencerthayer** [comment]
That's great news. So when will we see you include an entry for the V series?

**Comment by adophoxia** [comment]
Some time In the week after tomorrow.

**Comment by spencerthayer** [comment]
Oh thank beebus. I really do not like VIA.

**Comment by spencerthayer** [comment]
How is this coming along?

**Comment by adophoxia** [comment]
The PRs for most of the V series have been made, @spencerthayer
![image](https://user-images.githubusercontent.com/100170946/219550131-905b6d00-7e72-4de5-b976-3494e6ced377.png)

**Comment by spencerthayer** [comment]
Thank you!

**Comment by spencerthayer** [comment]
It doesn't look like `make keychron/v3/ansi_encoder:default` is a working command yet. I get that it will work if I pull the right branch but I'll leave open until all branches merge and default instructions work as written.

**Comment by adophoxia** [comment]
Tested compiling the `default` keymap for the `ansi_encoder` variant over on my [`vial`](https://github.com/adophoxia/vial-qmk) branch and it compiles fine for me.
![image](https://user-images.githubusercontent.com/100170946/219904493-9fdc21e6-42ed-4a91-b8c8-c2557f08c52a.png)

I suggest that you resync the branch.
