### ISSUE TITLE
Q6 Support

### ISSUE THREAD

**Issue by clanterns11** [adophoxia/VIAL-for-Keychron#5]
Hello, I came across Vial and your resort post while seeking more functionality from my Q6. Any plans to support it? I see you have most of the Q series except the Q6. I have the knob version. 

Any help is appreciated.

**Comment by adophoxia** [comment]
The Q6 is now in the main `vial-qmk` repo via the `vial` branch [`here`](https://github.com/vial-kb/vial-qmk/tree/vial/keyboards/keychron/q6).
