### ISSUE TITLE
Q0 Plus Support

### ISSUE THREAD

**Issue by zmiguel** [adophoxia/VIAL-for-Keychron#6]
Hi there!
First, thank you so much for the vial configs for keychron boards!

Is there any chance you could add the config for the newly released Q0 Plus numpad? It has a few extra keys and a knob, it's on the keychron repo under Q0 with [rev_0131](https://github.com/Keychron/qmk_firmware/tree/master/keyboards/keychron/q0/rev_0131)

Thank you!

**Comment by adophoxia** [comment]
@zmiguel, I actually had the Q0 Plus ported sometime earlier, so if you still want to build VIAL firmware for it, you can do so off of my [`branch`](https://github.com/adophoxia/vial-qmk/tree/vial-keychron-q0/keyboards/keychron/q0).

**Comment by zmiguel** [comment]
Completely missed it, my bad. I was looking at the general keychron branch and not the specific q0 one.

Thank you!
